export const UPDATE_POSTS = 'UPDATE_POSTS';

export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';

export const AUTHETICATE_USER = 'AUTHENTICATE_USER';

export const LOG_OUT = 'LOG_OUT';

export const CLEAR_AUTH_STATE = 'CLEAR_AUTH_STATE';

export const EDIT_USER_START = 'EDIT_USER_START';
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS';
export const EDIT_USER_FAILED = 'EDIT_USER_FAILED';

export const FETCH_USER_PROFILE_START = 'FETCH_USER_PROFILE_START';
export const FETCH_USER_PROFILE_SUCCESS = 'FETCH_USER_PROFILE_SUCCESS';
export const FETCH_USER_PROFILE_FAILED = 'FETCH_USER_PROFILE_FAILED';

export const FETCH_FRIENDS_SUCCESS = 'FETCH_FRIENDS_SUCCESS';
export const FETCH_FRIENDS_FAILED = 'FETCH_FRIENDS_FAILED';
export const ADD_FRIEND_SUCCESS = 'ADD_FRIEND_SUCCESS';
export const REMOVE_FRIEND_SUCCESS = 'REMOVE_FRIEND_SUCCESS';

export const ADD_POST = 'ADD_POST';
export const ADD_COMMENT = 'ADD_COMMENT';
export const ADD_POST_LIKE = 'ADD_POST_LIKE';

export const SEARCH_USERS_SUCCESS = 'SEARCH_USERS_SUCCESS';